# Generated by Django 4.2.7 on 2024-07-14 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_assured', models.IntegerField()),
                ('premium', models.IntegerField()),
                ('premium_frequency', models.CharField(choices=[('y', 'Yearly'), ('hy', 'Half-Yearly'), ('m', 'Monthly')], default='yearly', max_length=2)),
                ('pt', models.IntegerField()),
                ('ptt', models.IntegerField()),
                ('policy_type', models.CharField(blank=True, max_length=20, null=True)),
                ('policy_information', models.TextField(blank=True, null=True)),
                ('riders', models.CharField(blank=True, max_length=20, null=True)),
                ('premium_options', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins_app.profile')),
            ],
        ),
    ]
