# Generated by Django 4.2.7 on 2024-07-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
